version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Для горячей перезагрузки в Docker
      - VITE_API_URL=localhost:8000
    # Возвращаю к production запуску (убираю command или ставлю npm run build/start)
